### ISSUE TITLE
Build command fails

### ISSUE THREAD

**Issue by tooolbox** [jaz303/taylor#3]
Attempting to build a Swift CLI app with Taylor fails:

`npm install taylor`
`taylor create-app test`
`cd test`
`taylor build`

Result:
`<unknown>:0: error: unknown argument: '-O0'`
`<unknown>:0: error: unsupported option '-emit-library' for 'swift'; did you mean 'swiftc -emit-library'?`
`<unknown>:0: error: unsupported option '-o' for 'swift'; did you mean 'swiftc -o'?`
`make: *** [build/modules/libapp_main.dylib] Error 1`
`make exited with code 2`
`[Error: make exited with code 2]`
`Error: make exited with code 2
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/taylor/lib/actions/build_make_target.js:30:32)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)`

**Comment by jaz303** [comment]
Thanks will investigate this week
